#!/bin/bash
# File: cacador.sh
#  Time-stamp: <2013-10-10 01:02:03>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.



IMG_EXT="jpg jpeg png"

usage() (
    echo "$0   [OPTION...] <DIRECTORY>"
)

help() (
    usage
    echo "	-h Show this help message."
    echo "	-V Show the version."
    echo "	-T Title (default: Gallery)."
    echo "	-S Modify normal size (default: '800x')."
    echo "	-H Generate HTML files only."   

)



html=0
output=Images
extension=jpg
tiny_size=160x
normal_size=800x
title=Gallery
quality=80

tiny=tiny
normal=medium
orig=original

template=supersimple
stylesheet=templates/$template/style.css

output_tiny="$output/$tiny"
output_orig="$output/$orig"
output_normal="$output/$normal"
output_html="$output/html"

while getopts "hVS:HT:t:" Option


do
  case $Option in
    h) 	help
	exit 0
	;;
    V)	echo "Cacador v0.2 by OffWorlApps : https://github.com/OffWorldApps/ "
	exit 0
	;;
    S ) normal_size=$OPTARG
      ;;
    H) html=1
    ;;
    T) title=$OPTARG
    ;;
    t) template=$OPTARG
    ;;
  esac
done
shift $(($OPTIND - 1))

echo $normal_size


mkdir -p "$output"
mkdir -p "$output_normal"
mkdir -p "$output_tiny"
mkdir -p "$output_orig"
mkdir -p "$output_html"

for ext in $IMG_EXT
do
    find_filter="$find_filter -iname \"*.$ext\" -o"
done
find_filter="$find_filter -false"


files=$(eval find $1 $find_filter  | xargs echo)

cp $files $output_orig



for img in `ls $output_orig`
do
  i=$((${i}+1))
  liste[${i}]=$img
done

nombre_fichiers=$i
echo "$nombre_fichiers images"

j=0
k=0
l=0

for img in `ls $output_orig`
do
  j=$(($j+1))

  echo $img
   if [ $html -ne 1 ]
    then
      convert  -quality $quality   -auto-orient -resize $normal_size $output_orig/$img $output_normal/${img}_n.$extension
      convert  -quality $quality -auto-orient  -resize $tiny_size   $output_normal/${img}_n.$extension $output_tiny/${img}_p.$extension
   fi
  taille=`ls -lh  $output_orig/$img | cut -d " " -f5`
  if [ $j -gt 1 ]
    then
    k=$(($j-1))
    img_previous=${liste[$k]}
    link_previous="<a href=\"${img_previous}.html\"><img alt=\"Image précédente : $img_previous \" src=\"../$tiny/${img_previous}_p.$extension\"/></a>"
  fi 
  
  if [ $j -lt $nombre_fichiers ]
    then
      l=$(($j+1))
      img_next=${liste[$l]}
      link_next="<a href=\"${img_next}.html\"><img alt=\"Image suivante : $img_next \" src=\"../$tiny/${img_next}_p.$extension\"/></a>"
    else
      unset link_next
  fi  
    
  
cat <<EOF>"$output_html/$img.html"
<!DOCTYPE html>
<html>
  <head>
    <title>$title</title>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  </head>
  
  <body>
  <h1>$title</h1>
  <p><img alt="Image $img " src="../$normal/${img}_n.$extension"/>
 <p>$link_previous
  -
  $link_next</p>
  <p>Télécharger l'image originale : <a href="../$orig/$img">$img (${taille}o)</a></p>
  <p>Toutes les <a href="../index.html">images</a></p>
  <p>Ce dossier de photos est destiné à un usage privé, il sera donc bientôt effacé.</p>
</body>
</html>
EOF

done


index="$output/index.html"
echo "<!DOCTYPE html>" > $index
echo "<html>" >> "$index"
echo "<head>" >> "$index"
echo "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />" >> "$index"
echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"html/style.css\">" >> "$index"
echo "  <link rel=\"shortcut icon\" type=\"image/png\" href=\"favicon.png\">" >> "$index"
echo "  <title>$title</title>" >> "$index"
echo "</head>" >> "$index"
echo "<body>" >> "$index"

echo "  <h1>$title</h1>" >> "$index"

for img in `ls  $output_orig`
do
echo "  <a href=\"html/${img}.html\"><img alt=\"$img \" src=\"$tiny/${img}_p.$extension\"/></a>" >> "$index"

done 

echo "</body>" >> "$index"
echo "</html>" >> "$index"

cp $stylesheet $output_html
